### ISSUE TITLE
Bottom stiffener blocks the hip motor from entering the torso

### ISSUE THREAD

**Issue by kzorina** [tasts-robots/upkie_parts#12]
[Bottom stiffener](https://github.com/tasts-robots/upkie_parts/blob/main/3d_printing/torso/stiffener_bottom.stl) needs to be adjusted
![image](https://github.com/tasts-robots/upkie_parts/assets/32056733/bdd6ab83-29a4-427e-8344-2c1d2db79f1d)

**Comment by stephane-caron** [comment]
Fixed yesterday https://github.com/tasts-robots/upkie_parts/pull/13, Michel Strogoff's torso is now fully assembled :wrench:
